//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.21 at 02:42:33 AM CET 
//


package org.essembeh.rtfm.model.configuration.core.version1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TAttributeArray complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAttributeArray">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attribute" type="{http://rtfm.essembeh.org/ConfigurationCore-v1}TFixedAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="regex-attribute" type="{http://rtfm.essembeh.org/ConfigurationCore-v1}TRegexAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAttributeArray", namespace = "http://rtfm.essembeh.org/ConfigurationCore-v1", propOrder = {
    "attribute",
    "regexAttribute"
})
@XmlSeeAlso({
    TAttributeSet.class
})
public class TAttributeArray {

    @XmlElement(namespace = "http://rtfm.essembeh.org/ConfigurationCore-v1")
    protected List<TFixedAttribute> attribute;
    @XmlElement(name = "regex-attribute", namespace = "http://rtfm.essembeh.org/ConfigurationCore-v1")
    protected List<TRegexAttribute> regexAttribute;

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TFixedAttribute }
     * 
     * 
     */
    public List<TFixedAttribute> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<TFixedAttribute>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the regexAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regexAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegexAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRegexAttribute }
     * 
     * 
     */
    public List<TRegexAttribute> getRegexAttribute() {
        if (regexAttribute == null) {
            regexAttribute = new ArrayList<TRegexAttribute>();
        }
        return this.regexAttribute;
    }

}
